version: "3.9"
services:
  redis:
    image: "redis:7"

  config-server:
    image: config-server:latest
    build:
      context: ./ConfigServer
    ports:
      - 8081:8080
    environment:
      REDIS_HOST: redis

  antivirus:
    image: antivirus:latest
    build:
      context: ./Antivirus
    ports:
      - 8080:8080
    environment:
      CONFIG_SERVICE_ENDPOINT: http://config-server:8080
